version: '3.8'
services:
  dsx-apps-backend:
    build: ./backend
    container_name: dsx-apps-backend-container
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start

  dsx-apps-client:
    build: ./client
    container_name: dsx-apps-client-container
    ports:
      - '3000:3000'
    volumes:
      - ./client:/usr/src/app
      - /usr/src/app/node_modules
    command: npm start
    stdin_open: true
    tty: true
