version: '3.8'
services:
  folder-templates-backend:
    build: ./backend
    container_name: folder-templates-backend-container
    ports:
      - '8080:8080'
    volumes:
      - ./backends:/app

  folder-templates-client:
    build: ./client
    container_name: folder-templates-client-container
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
    stdin_open: true
    tty: true
